[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback so React Router can handle /admin and other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
